//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int InvoiceItemId { get; set; }
        public Nullable<int> InvoiceItemCount { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<long> InvoiceItemFeeSell { get; set; }
        public Nullable<long> InvoiceItemPurchFee { get; set; }
        public Nullable<int> Invoiceid { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
