//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_invoice
    {
        public int InvoiceId { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<long> InvoicePrice { get; set; }
        public string InvoiceDescription { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<long> InvoicePrice_purch { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTell { get; set; }
        public string FullName { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<byte> InvoiceType { get; set; }
        public string InvoiceTypeFarsi { get; set; }
    }
}
