//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_userlog
    {
        public int UserLogId { get; set; }
        public string ComputerName { get; set; }
        public string IPAddress { get; set; }
        public string EnterDateTime { get; set; }
        public string ExitDateTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string FullName { get; set; }
    }
}
